import Head from "next/head";
import { Canvas } from "@react-three/fiber";

import WaveBanner from "../components/three/entities/Banner/WaveBanner";
import { Suspense } from "react";
import Layer from "../components/layers/Layer";

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layer.Container backgroundColor="#cccccc">
        <Canvas camera={{ fov: 12, position: [0, 0, 5] }}>
          <Suspense fallback={null}>
            <WaveBanner />
          </Suspense>
        </Canvas>
      </Layer.Container>
    </div>
  );
}

export default Home;
